name: Deploy to Shared Hosting

on:
  push:
    tags:
      - "v*"   # contoh: v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Nuxt in production
      - name: Build Nuxt
        run: npm run build

      # Prepare deploy dir (gabungkan .output + node_modules + package.json)
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r .output deploy/.output
          cp -r node_modules deploy/node_modules
          cp package.json deploy/package.json
          cp package-lock.json deploy/package-lock.json

      # Deploy via FTP
      - name: Upload build via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: "deploy/"
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}